config/routes.rb
Onering::Application.routes.draw do
  root :to              => "pages#home",             :as => :home
  get 'learn_more'      => "pages#learn_more",       :as => :learn_more
  get "about"           => "pages#about",            :as => :about
  get "for_business"    => "pages#for_business",     :as => :store
  get "employees"       => "pages#employees",        :as => :employee
  get "security"        => "pages#security",         :as => :security
  get "privacy"         => "pages#privacy",          :as => :privacy
  get "contact"         => "pages#contact",          :as => :contact


  # OmniAuth Provider paths
  #-----------------------------------------------------------------
  match '/oauth/authorize' => 'auth#authorize', :as => :authorization
  match '/oauth/access_token' => 'auth#access_token'
  match '/oauth/customer' => 'auth#customer'

  # Customer Namespace
  #-----------------------------------------------------------------
  devise_for :customers, :path => 'customer', :controllers => {
    :confirmations => 'customer/confirmations',
    :passwords => 'customer/passwords',
    :registrations => 'customer/registrations',
    :sessions => 'customer/sessions',
    :unlocks => 'customer/unlocks'
  }

  devise_scope :customer do
    get '/customer/scope_conflict' => 'customer/sessions#scope_conflict'
    delete '/customer/resolve_conflict' => 'customer/sessions#resolve_conflict'
    delete '/customer/cancel_account' => 'customer/registrations#cancel_account'
  end

  namespace :customer do
    root :to                  => "pages#home", :as => :home
    resources :payment_profiles, :path => "payment_methods"
    resources :payments, :only => [:index, :new, :create]
    resources :applications, :only => [:index, :show, :edit, :update, :destroy] do
      member do
        put 'claim'         => "applications#claim", :as => :claim
      end
    end
  end

  # Store Namespace
  #-----------------------------------------------------------------
  devise_for :stores, :path => 'store', :controllers => {
    :confirmations => 'store/confirmations',
    :passwords => 'store/passwords',
    :registrations => 'store/registrations',
    :sessions => 'store/sessions',
    :unlocks => 'store/unlocks'
  }

  devise_scope :store do
    get '/store/scope_conflict' => 'store/sessions#scope_conflict'
    delete '/store/resolve_conflict' => 'store/sessions#resolve_conflict'
    delete '/store/cancel_account' => 'store/registrations#cancel_account'
  end

  namespace :store do
    root :to                  => "pages#home", :as => :home
    resources :applications
  end

  # Employee Namespace
  #-----------------------------------------------------------------
  devise_for :employees, :path => 'employee', :controllers => {
    :confirmations => 'employee/confirmations',
    :passwords => 'employee/passwords',
    :registrations => 'employee/registrations',
    :sessions => 'employee/sessions',
    :unlocks => 'employee/unlocks'
  }

  devise_scope :employee do
    get '/employee/scope_conflict' => 'employee/sessions#scope_conflict'
    delete '/employee/resolve_conflict' => 'employee/sessions#resolve_conflict'
    delete '/employee/cancel_account' => 'employee/registrations#cancel_account'
  end

  namespace :employee do
    root :to                  => "pages#home", :as => :home
    resources :employees
    resources :stores do
      member do
        put 'approve'         => "stores#approve", :as => :approve
      end
    end
  end

  # SSO Clients
  #------------------------------------------------------------------
  resources :clients

  # API
  #------------------------------------------------------------------
  mount OneRing::APIv1 => "/"

  match "*path" => 'routing_errors#not_found'
end

app/models/customers/payment_observer.rb
class PaymentObserver < ActiveRecord::Observer
  observe :payment

  # Before Create
  #----------------------------------------------------------------------------
  def before_create(payment)
    service = AuthorizeNetService.new
    unless (payment.payment_profile.nil?)
      begin
        service.create_cim_customer_profile_transaction(payment.payment_profile, payment.amount)
      rescue => e
        AdminNotificationMailer.authorize_net_error(payment, e).deliver
        return false
      end
    end
  end
  
  # After Create
  #----------------------------------------------------------------------------
  def after_create(payment)
#    AdminNotificationMailer.new_user(customer).deliver
  end
end

app/controllers/customer/application_controller.rb
class Customer::ApplicationController < ::ApplicationController
  layout 'customer_application'
  before_filter :check_scope_conflict

  before_filter :authenticate_customer!
  before_filter :get_customer

  def current_user
    @current_user = current_customer unless current_customer.nil?
  end
  
  def get_customer
    @current_customer = current_customer
  end

  private
  def check_scope_conflict
    redirect_to home_path if (!(current_user.nil?) && (current_customer.nil?))
  end
end

app/controllers/customer/applications_controller.rb
class Customer::ApplicationsController < Customer::BaseController
  include ActiveModel::ForbiddenAttributesProtection
  load_and_authorize_resource

  # GET /store/applications
  #-----------------------------------------------------------------------
  def index
    @applications = Application.all
    respond_with(:customer, @applications)
  end

  # GET /store/applications/1
  #-------------------------------------------------------------------
  def show
    @application = Application.find(params[:id])
    respond_with(:customer, @application)
  end
  
  # PUT /store/applications/1/claim
  #-------------------------------------------------------------------
  def claim
    @application = Application.find(params[:id])
    @application.customer_account_number = current_customer.account_number

    if @application.claim
      flash[:notice] = "Successfully claimed application."
    else
      flash[:alert] = YAML.load_file("#{Rails.root}/config/locales/devise.en.yml")['en']['devise']['failure']['invalid_data']
    end
    respond_with(:customer, @application)
  end

  # GET /store/applications/1/edit
  #-------------------------------------------------------------------
  def edit
    @product_types = ["Tire"]
    @application = Application.find(params[:id])
    respond_with(:customer, @application)
  end

  # PUT /employee/applications/1
  #-----------------------------------------------------------------
  def update
    @product_types = ["Tire"]
    @application = Application.find(params[:id])

    if @application.update_attributes(update_application_params)
      flash[:notice] = "Successfully updated application."
      if @application.submit
        credit_decision = CreditDecision.new(:application => @application)
        if credit_decision.save
          @application.approve
          flash[:alert] = "Application approved."
        end
      else
        flash[:alert] = "Submission Unsuccessful."
      end
    else
      flash[:notice] = "Updating application failed."
    end
    respond_with(:customer, @application)
  end
  
  # DELETE /store/applications/1
  #-------------------------------------------------------------------
  def destroy
    @application = Application.find(params[:id])
    @application.destroy
    flash[:notice] = "Successfully destroyed application."
    respond_with(:customer, @application)
  end

  private
  def update_application_params
    params.require(:application).permit( 
      :time_at_address, :rent_or_own, :rent_payment )
  end
end

app/controllers/customer/auth_controller.rb
class Customer::AuthController < Customer::ApplicationController
  before_filter :authenticate_customer!, :except => [:access_token]
  skip_before_filter :verify_authenticity_token, :only => [:access_token]

  #TODO: re-evaluate this; maybe this is how I controll access for each client?
  skip_authorization_check

  # GET /authorize
  def authorize
    AccessGrant.prune!
    access_grant = current_customer.access_grants.create({:client => application, :state => params[:state]}, :without_protection => true)
    redirect_to access_grant.redirect_uri_for(params[:client_id])
  end

  # GET /access_token
  def access_token
    application = Client.authenticate(params[:client_id], params[:client_secret])

    if application.nil?
      render :json => {:error => "Could not find application"}
      return
    end

    access_grant = AccessGrant.authenticate(params[:code], application.id)
    if access_grant.nil?
      render :json => {:error => "Could not authenticate access code"}
      return
    end

    access_grant.start_expiry_period!
    render :json => {:access_token => access_grant.access_token, :refresh_token => access_grant.refresh_token, :expires_in => Devise.timeout_in.to_i}
  end

  def failure
    render :text => "ERROR: #{params[:message]}"
  end

  def customer
    hash = {
      :provider => 'credda',
      :id => current_customer.id.to_s,
      :info => {
         :email      => current_customer.email,
      },
      :extra => {
         :first_name => current_customer.first_name,
         :last_name  => current_customer.last_name
      }
    }

    render :json => hash.to_json
  end

  # Incase, we need to check timeout of the session from a different application!
  # This will be called ONLY if the user is authenticated and token is valid
  # Extend the UserManager session
  def isalive
    warden.set_user(current_customer, :scope => :customer)
    response = { 'status' => 'ok' }

    respond_to do |format|
      format.any { render :json => response.to_json }
    end
  end

  protected
  def application
    @application ||= Client.find_by_app_id(params[:client_id])
  end
end

app/controllers/customer/base_controller.rb
class Customer::BaseController < ::ApplicationController
  layout 'customer_layout'
  before_filter :authenticate_customer!
  before_filter :get_customer

  def current_user
    @current_user = current_customer unless current_customer.nil?
  end
  
  def get_customer
    @current_customer = current_customer
  end

  private
end

app/controllers/customer/confirmations_controller.rb
class Customer::ConfirmationsController < Devise::ConfirmationsController
  include ActiveModel::ForbiddenAttributesProtection
  # Authentication filters
  prepend_before_filter :require_no_authentication, :only => [ :new, :create, :show ]
  before_filter :check_scope_conflict

  # GET /resource/confirmation/new
  def new
    @customer = Customer.new
  end

  # POST /resource/confirmation
  def create
    @customer = Customer.send_confirmation_instructions(create_customer_params)

    if successfully_sent?(@customer)
      respond_with({}, :location => home_path)
    else
      respond_with(@customer)
    end
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    @customer = Customer.confirm_by_token(params[:confirmation_token])

    if @customer.errors.empty?
      set_flash_message(:notice, :confirmed) if is_navigational_format?
      sign_in(:customer, @customer)
      redirect_to customer_home_path
    else
      respond_with_navigational(@customer.errors, :status => :unprocessable_entity){ render :new }
    end
  end

  protected
  def check_scope_conflict
    redirect_to customer_scope_conflict_path if (!(current_user.nil?) && (current_customer.nil?))
  end

  def after_sign_in_path_for(customer)
    customer_home_path
  end

  private
  def create_customer_params
    params.require(:customer).permit(:email)
  end
end

app/controllers/customer/credit_cards_controller.rb
class Customer::CreditCardsController < Customer::BaseController
  include ActiveModel::ForbiddenAttributesProtection
  load_and_authorize_resource

  # GET /customer/credit_cards
  #-----------------------------------------------------------------------
  def index
    @credit_cards = current_customer.payment_profiles
    respond_with(:customer, @credit_cards)
  end
  
  # GET /customer/credit_cards/new
  #-------------------------------------------------------------------
  def new
    @credit_card = PaymentProfile.new
    @credit_card.build_credit_card
    @credit_card.build_billing_address
    respond_with(:customer, @credit_card)
  end

  # POST /customer/credit_cards
  #-------------------------------------------------------------------
  def create
    @credit_card = PaymentProfile.new(create_payment_profile_params)
    @credit_card.customer = current_customer
    if @credit_card.save
      flash[:notice] = "Successfully linked credit card."  
    else
      flash[:alert] = YAML.load_file("#{Rails.root}/config/locales/devise.en.yml")['en']['devise']['failure']['invalid_data']
    end
    respond_with(:customer, @credit_card)
  end

  # GET /customer/payment_profiles/1/edit
  #-------------------------------------------------------------------
  def edit
    @credit_card = PaymentProfile.find(params[:id])
    respond_with(:customer, @credit_card)
  end

  # PUT /customer/payment_profiles/1
  #-----------------------------------------------------------------
  def update
    @credit_card = PaymentProfile.find(params[:id])
    
    if @credit_card.update_attributes(update_payment_profile_params)
      flash[:notice] = "Successfully updated credit card."
    else
      flash[:notice] = "Updating payment profile failed."
    end
    respond_with(:customer, @credit_card)
  end
  
  # DELETE /customer/payment_profiles/1
  #-------------------------------------------------------------------
  def destroy
    @credit_card = PaymentProfile.find(params[:id])
    @credit_card.destroy
    flash[:notice] = "Successfully deleted payment profile."  
    respond_with(:customer, @credit_card)
  end

  private
  def create_credit_card_params
    params.require(:credit_card).permit(
      :first_name, :last_name, :payment_type, 
      {:billing_address_attributes  => [:street, :city, :state, :zip_code, :country]}, 
      {:credit_card_attributes  => [:brand, :credit_card_number, :expiration_date, :ccv_number]} )
  end

  def update_credit_card_params
    params.require(:credit_card).permit(
      :first_name, :last_name, :payment_type, 
      {:billing_address_attributes  => [:street, :city, :state, :zip_code, :country]}, 
      {:credit_card_attributes  => [:brand, :credit_card_number, :expiration_date, :ccv_number]} )
  end
end

app/controllers/customer/pages_controller.rb
class Customer::PagesController < Customer::BaseController
#  before_filter :authenticate_customer!
  skip_authorization_check

  def home
    @matching_applications = current_customer.possible_unclaimed_applications
    @contract_details = [
      { :name => "Contract 1",
        :description => "Contract for some Tires",
        :total => BigDecimal.new("1600"),
        :paid_off => BigDecimal.new("600") },
      { :name => "Contract 2",
        :description => "Contract for some Watches",
        :total => BigDecimal.new("2200"),
        :paid_off => BigDecimal.new("1900") }
    ]
    
    respond_to do |format|
      format.json { }   
      format.xml  { }
      format.html  # this renders home.html.erb
    end 
  end  

  private
end

app/controllers/customer/passwords_controller.rb
class Customer::PasswordsController < Devise::PasswordsController
  include ActiveModel::ForbiddenAttributesProtection

  prepend_before_filter :require_no_authentication
  # Render the #edit only if coming from a reset password email link
  append_before_filter :assert_reset_token_passed, :only => :edit
  before_filter :check_scope_conflict

  # GET /customer/password/new
  def new
    @customer = Customer.new
  end

  # POST /customer/password
  def create
    @customer = Customer.send_reset_password_instructions(create_customer_params)

    if successfully_sent?(@customer)
      respond_with({}, :location => new_customer_session_path)
    else
      respond_with(@customer)
    end
  end

  # GET /customer/password/edit?reset_password_token=abcdef
  def edit
    @customer = Customer.find_or_initialize_with_error_by(:reset_password_token, params[:reset_password_token])
    if @customer.errors.empty?
      respond_with(@customer)
    else
      set_flash_message :alert, :invalid_reset_token
      redirect_to new_customer_session_path
    end
  end

  # PUT /customer/password
  def update
    @customer = Customer.reset_password_by_token(update_customer_params)

    if @customer.errors.empty?
      @customer.unlock_access! if unlockable?(@customer)
      flash_message = @customer.active_for_authentication? ? :updated : :updated_not_active
      set_flash_message(:notice, flash_message)
      sign_in(:customer, @customer)
      respond_with @customer, :location => customer_home_path
    else
      respond_with @customer
    end
  end

  protected
  def check_scope_conflict
    redirect_to customer_scope_conflict_path if (!(current_user.nil?) && (current_customer.nil?))
  end

  def after_sign_in_path_for(customer)
    customer_home_path
  end

  # Check if a reset_password_token is provided in the request
  def assert_reset_token_passed
    if params[:reset_password_token].blank?
      set_flash_message(:error, :no_token)
      redirect_to new_customer_session_path
    end
  end

  # Check if proper Lockable module methods are present & unlock strategy
  # allows to unlock customer on password reset
  def unlockable?(customer)
    customer.respond_to?(:unlock_access!) &&
      customer.respond_to?(:unlock_strategy_enabled?) &&
      customer.unlock_strategy_enabled?(:email)
  end

  private
  def create_customer_params
    params.require(:customer).permit(:email)
  end

  def update_customer_params
    params.require(:customer).permit(:reset_password_token, :password, :password_confirmation)
  end
end

app/views/customer/payment_profiles/_bank_account_form.html.haml
= nested_form_for( @payment_profile, :url => customer_payment_profiles_path, :method => :post, :html => { :class => '' } ) do |f|
  %fieldset
    %legend Account Information
    .row
      = f.hidden_field :payment_type, :value => "bank_account"
    .row
      .six.columns 
        = f.label "First Name"
        = f.text_field :first_name, :placeholder => "Elvis"
      .six.columns 
        = f.label "Last Name"
        = f.text_field :last_name, :placeholder => "Presley"
  %fieldset
    %legend Bank Account Details
    = f.fields_for :bank_account do |bank_account|
      .row
        .six.columns
          = bank_account.label "Account Holder"
          = bank_account.select :account_holder, :collection => ["personal", "business"]
        .six.columns
          = bank_account.label "Account Type"
          = bank_account.select :account_type, :collection => ["checking", "savings"]
      .row
        .six.columns
          = bank_account.label "Account Number"
          = bank_account.text_field :account_number
        .six.columns
          = bank_account.label "Routing Number"
          = bank_account.text_field :routing_number
  %fieldset
    %legend Address
    = f.fields_for :billing_address do |address|
      .row
        .twelve.columns
          = address.label "Street"
          = address.text_field :street, :placeholder => "123 Famous St."
      .row
        .six.columns
          = address.label "City"
          = address.text_field :city, :placeholder => "Charleston"
        .three.columns
          = address.label "State"
          = address.select :state, us_states, {}
        .three.columns
          = address.label "Zip Code"
          = address.text_field :zip_code, :placeholder => "11111"
      .row
        .twelve.columns
          = address.label "Country"
          = address.select :country, countries, {}
  = f.button :submit, :label => 'Save', :value => 'Save', :class => 'button radius'

app/views/customer/payment_profiles/_bank_account_form.html.slim
= nested_form_for( @payment_profile, :url => customer_payment_profiles_path(:anchor => "bank"), :method => :post, :html => { :class => '' } ) do |f|
  fieldset
    legend Account Information
    div.row
      = f.hidden_field :payment_type, :value => "bank_account"
    div.row
      div.large-6.columns 
        = f.label "First Name"
        = f.text_field :first_name, :placeholder => "Elvis"
      div.large-6.columns 
        = f.label "Last Name"
        = f.text_field :last_name, :placeholder => "Presley"
  fieldset
    legend Bank Account Details
    = f.fields_for :bank_account do |bank_account|
      div.row
        div.large-6.columns
          = bank_account.label "Account Holder"
          = bank_account.select :account_holder, :collection => ["personal", "business"]
        div.large-6.columns
          = bank_account.label "Account Type"
          = bank_account.select :account_type, :collection => ["checking", "savings"]
      div.row
        div.large-6.columns
          = bank_account.label "Account Number"
          = bank_account.text_field :account_number
        div.large-6.columns
          = bank_account.label "Routing Number"
          = bank_account.text_field :routing_number
  fieldset
    legend Address
    = f.fields_for :billing_address do |address|
      div.row
        div.large-12.columns
          = address.label "Street"
          = address.text_field :street, :placeholder => "123 Famous St."
      div.row
        div.large-6.columns
          = address.label "City"
          = address.text_field :city, :placeholder => "Charleston"
        div.large-3.columns
          = address.label "State"
          = address.select :state, us_states, {}
        div.large-3.columns
          = address.label "Zip Code"
          = address.text_field :zip_code, :placeholder => "11111"
      div.row
        div.large-12.columns
          = address.label "Country"
          = address.select :country, countries, {}
  = f.button :submit, :label => 'Save', :value => 'Save', :class => 'button radius'

app/views/customer/payment_profiles/_credit_card_form.html.haml
= nested_form_for( @payment_profile, :url => customer_payment_profiles_path, :method => :post, :html => { :class => '' } ) do |f|
  %fieldset
    %legend Account Information
    .row
      = f.hidden_field :payment_type, :value => "credit_card"
    .row
      .six.columns 
        = f.label "First Name"
        = f.text_field :first_name, :placeholder => "Elvis"
      .six.columns 
        = f.label "Last Name"
        = f.text_field :last_name, :placeholder => "Presley"
  %fieldset
    %legend Credit Card Details
    = f.fields_for :credit_card do |credit_card|
      .row
        .four.columns
          = credit_card.label "Brand"
          = credit_card.select :brand, :collection => ["mastercard", "visa"]
        .eight.columns
          = credit_card.label "Credit Card Number"
          = credit_card.text_field :credit_card_number
      .row
        .six.columns
          = credit_card.label "Expiration Date"
          = credit_card.date_select :expiration_date, :order => [:month, :year], :start_year => Time.now.year
        .six.columns
          = credit_card.label "CCV Number"
          = credit_card.text_field :ccv_number
  %fieldset
    %legend Address
    = f.fields_for :billing_address do |address|
      .row
        .twelve.columns
          = address.label "Street"
          = address.text_field :street, :placeholder => "123 Famous St."
      .row
        .six.columns
          = address.label "City"
          = address.text_field :city, :placeholder => "Charleston"
        .three.columns
          = address.label "State"
          = address.select :state, us_states, {}
        .three.columns
          = address.label "Zip Code"
          = address.text_field :zip_code, :placeholder => "11111"
      .row
        .twelve.columns
          = address.label "Country"
          = address.select :country, countries, {}
  = f.button :submit, :label => 'Save', :value => 'Save', :class => 'button radius'

app/views/customer/payment_profiles/_credit_card_form.html.slim
= nested_form_for( @payment_profile, :url => customer_payment_profiles_path(:anchor => "card"), :method => :post, :html => { :class => '' } ) do |f|
  fieldset
    legend Account Information
    div.row
      = f.hidden_field :payment_type, :value => "credit_card"
    div.row
      div.large-6.columns 
        = f.label "First Name"
        = f.text_field :first_name, :placeholder => "Elvis"
      div.large-6.columns 
        = f.label "Last Name"
        = f.text_field :last_name, :placeholder => "Presley"
  fieldset
    legend Credit Card Details
    = f.fields_for :credit_card do |credit_card|
      div.row
        div.large-4.columns
          = credit_card.label "Brand"
          = credit_card.select :brand, :collection => ["mastercard", "visa"]
        div.large-8.columns
          = credit_card.label "Credit Card Number"
          = credit_card.text_field :credit_card_number
      div.row
        div.large-6.columns
          = credit_card.label "Expiration Date"
          = credit_card.date_select :expiration_date, :order => [:month, :year], :start_year => Time.now.year
        div.large-6.columns
          = credit_card.label "CCV Number"
          = credit_card.text_field :ccv_number
  fieldset
    legend Address
    = f.fields_for :billing_address do |address|
      div.row
        div.large-12.columns
          = address.label "Street"
          = address.text_field :street, :placeholder => "123 Famous St."
      div.row
        div.large-6.columns
          = address.label "City"
          = address.text_field :city, :placeholder => "Charleston"
        div.large-6.columns
          = address.label "State"
          = address.select :state, us_states, {}
        div.large-3.columns
          = address.label "Zip Code"
          = address.text_field :zip_code, :placeholder => "11111"
      div.row
        div.large-12.columns
          = address.label "Country"
          = address.select :country, countries, {}
  = f.button :submit, :label => 'Save', :value => 'Save', :class => 'button radius'

app/views/customer/payment_profiles/index.html.slim
= provide(:title, "Payment Accounts")

h1 Currently linked Payment Accounts
- if (@payment_profiles.nil?) || (@payment_profiles.empty?)
  p You currently have no linked accounts.  Please add a payment account.
- else
  table.table.table-striped.table-hover
    thead
      tr
        th Type
        th Account
        th
    tbody
      - @payment_profiles.each do |payment_profile|
        tr
          td = payment_profile.payment_type
          td = payment_profile.name
= link_to "Link New Account", new_customer_payment_profile_path, :class => 'button radius'

app/views/customer/payment_profiles/new.html.slim
= provide(:title, "New Payment Account")

div.row
  div.large-8.columns
    h2 New Payment Method
    div.section-container.tabs[data-section data-options="deep_linking: true"]
      section.section
        p.title
          = link_to "Credit Card", "#card", :id => 'creditCard'
        div.content[data-slug="card"]
          = render "credit_card_form"
      section.section
        p.title
          = link_to "Bank Account", "#bank", :id => 'creditCard'
        div.content[data-slug="bank"]
          = render "bank_account_form"