config/routes.rb
Onering::Application.routes.draw do
  root :to              => "pages#home",             :as => :home
  get 'learn_more'      => "pages#learn_more",       :as => :learn_more
  get "about"           => "pages#about",            :as => :about
  get "for_business"    => "pages#for_business",     :as => :store
  get "employees"       => "pages#employees",        :as => :employee
  get "security"        => "pages#security",         :as => :security
  get "privacy"         => "pages#privacy",          :as => :privacy
  get "contact"         => "pages#contact",          :as => :contact


  # OmniAuth Provider paths
  #-----------------------------------------------------------------
  match '/oauth/authorize' => 'auth#authorize', :as => :authorization
  match '/oauth/access_token' => 'auth#access_token'
  match '/oauth/customer' => 'auth#customer'

  # Customer Namespace
  #-----------------------------------------------------------------
  devise_for :customers, :path => 'customer', :controllers => {
    :confirmations => 'customer/confirmations',
    :passwords => 'customer/passwords',
    :registrations => 'customer/registrations',
    :sessions => 'customer/sessions',
    :unlocks => 'customer/unlocks'
  }

  devise_scope :customer do
    get '/customer/scope_conflict' => 'customer/sessions#scope_conflict'
    delete '/customer/resolve_conflict' => 'customer/sessions#resolve_conflict'
    delete '/customer/cancel_account' => 'customer/registrations#cancel_account'
  end

  namespace :customer do
    root :to                  => "pages#home", :as => :home
    resources :payment_profiles, :path => "payment_methods"
    resources :payments, :only => [:index, :new, :create]
    resources :applications, :only => [:index, :show, :edit, :update, :destroy] do
      member do
        put 'claim'         => "applications#claim", :as => :claim
      end
    end
  end

  # Store Namespace
  #-----------------------------------------------------------------
  devise_for :stores, :path => 'store', :controllers => {
    :confirmations => 'store/confirmations',
    :passwords => 'store/passwords',
    :registrations => 'store/registrations',
    :sessions => 'store/sessions',
    :unlocks => 'store/unlocks'
  }

  devise_scope :store do
    get '/store/scope_conflict' => 'store/sessions#scope_conflict'
    delete '/store/resolve_conflict' => 'store/sessions#resolve_conflict'
    delete '/store/cancel_account' => 'store/registrations#cancel_account'
  end

  namespace :store do
    root :to                  => "pages#home", :as => :home
    resources :applications
  end

  # Employee Namespace
  #-----------------------------------------------------------------
  devise_for :employees, :path => 'employee', :controllers => {
    :confirmations => 'employee/confirmations',
    :passwords => 'employee/passwords',
    :registrations => 'employee/registrations',
    :sessions => 'employee/sessions',
    :unlocks => 'employee/unlocks'
  }

  devise_scope :employee do
    get '/employee/scope_conflict' => 'employee/sessions#scope_conflict'
    delete '/employee/resolve_conflict' => 'employee/sessions#resolve_conflict'
    delete '/employee/cancel_account' => 'employee/registrations#cancel_account'
  end

  namespace :employee do
    root :to                  => "pages#home", :as => :home
    resources :employees
    resources :stores do
      member do
        put 'approve'         => "stores#approve", :as => :approve
      end
    end
  end

  # SSO Clients
  #------------------------------------------------------------------
  resources :clients

  # API
  #------------------------------------------------------------------
  mount OneRing::APIv1 => "/"

  match "*path" => 'routing_errors#not_found'
end

app/models/applications/application.rb
class Application < ActiveRecord::Base
  include ActiveModel::Validations
  extend Enumerize
  
  # Associations
  #----------------------------------------------------------------------------
  has_many :products, :inverse_of => :application
  accepts_nested_attributes_for :products
  has_many :terms_options, :inverse_of => :application
  accepts_nested_attributes_for :terms_options
  has_one :credit_decision, :inverse_of => :application

  # Accessible Methods
  #----------------------------------------------------------------------------
  attr_accessible :customer_account_number, :store_account_number, :matching_email,
                  :products, :products_attributes, :time_at_address, :rent_or_own, :rent_payment,
                  :terms_options, :id_verified

  # Validations
  #----------------------------------------------------------------------------
  validates :products, :presence => true
  validates_associated :products
  before_validation :generate_application_number, :on => :create
  validates :application_number, :presence => true, :uniqueness => true

  # State Machine
  #----------------------------------------------------------------------------
  state_machine :state, :initial => :unclaimed do
    # Events
    #--------------------------------------------------------------------------
    event :claim do
      transition :unclaimed => :claimed
    end

    event :submit do
      transition :claimed => :submitted
    end

    event :deny do
      transition [:submitted, :approved, :finalized] => :denied
    end

    event :approve do
      transition [:submitted, :denied] => :approved
    end

    event :finalize do
      transition :approved => :finalized
    end

    event :complete do
      transition :finalized => :completed
    end

    # State Validations & Functions
    #--------------------------------------------------------------------------
    state all do
      validates :store_account_number, :presence => true, :immutable => true
      validates :matching_email, :presence => true
    end

    state all - [:unclaimed] do
      validates :customer_account_number, :presence => true, :immutable => true
    end

    state all - [:unclaimed, :claimed] do
      validates :time_at_address, :presence => true
      validates :rent_or_own, :presence => true
      validates :rent_payment, :presence => true
#      validate :customer_has_income_sources
    end

    state all - [:unclaimed, :claimed, :submitted] do
      validates :credit_decision, :presence => true
    end
    
    state all - [:unclaimed, :claimed, :submitted, :approved, :denied] do
      validates :terms_options, :presence => true
      validates :id_verified, :presence => true, :inclusion => { :in => [true] }
    end

    state :completed do
#      validates :contract_number, :presence => true
    end
  end

  # Named Scopes
  #----------------------------------------------------------------------------
  scope :unclaimed,  where(:state => "unclaimed").order('created_at ASC')
  scope :claimed,    where(:state => "claimed").order('created_at ASC')
  scope :submitted,  where(:state => "submitted").order('created_at ASC')
  scope :approved,   where(:state => "approved").order('created_at ASC')
  scope :denied,     where(:state => "denied").order('created_at ASC')
  scope :finalized,  where(:state => "finalized").order('created_at ASC')
  scope :completed,  where(:state => "completed").order('created_at ASC')

  # Private Methods
  #----------------------------------------------------------------------------
  def store_name
    store = Store.where(:account_number => self.store_account_number).first
    store.name
  end

  def name
    return "#{self.store_name}: #{self.products_list}"
  end

  def products_list
    return self.products.map(&:name).join(", ")
  end

  def products_total_price
    total = BigDecimal.new("0.0")
    self.products.each do |product|
      total += product.price
    end
    return total
  end


  private
=begin
  def customer_has_income_sources
    if self.customer.nil?
      errors.add(:customer, "is required.")
    elsif self.customer.income_sources.empty?
      errors.add(:customer, "does not have any listed income sources.")
    end
  end
=end
  private
  def generate_application_number
    if self.application_number.nil?
      begin
        token = 'LTOAPP' + SecureRandom.hex(5).upcase
      end if Application.where({:application_number => token}).empty?
      self.application_number = token
    end
  end
end

app/models/applications/credit_decision.rb
class CreditDecision < ActiveRecord::Base
  include ActiveModel::Validations
  extend Enumerize

  # Association
  #----------------------------------------------------------------------------
  belongs_to :application
  
  # Attributes
  #----------------------------------------------------------------------------
  attr_accessible :application

  # Validations
  #----------------------------------------------------------------------------
  before_validation :set_status
  enumerize :status, :in => [:pending, :approved, :denied]
  validates :application, :presence => true, :immutable => true
  validates :status, :presence => true, :inclusion => { :in => ['pending', 'approved', 'denied'] }

  # Public Instance Methods
  #----------------------------------------------------------------------------

  # Private Methods
  #----------------------------------------------------------------------------
  private
  def set_status
    self.status ||= "pending"
  end
end

app/models/applications/products/tire.rb
class Tire < Product
  include ActiveModel::Validations

  validates :id_number, :presence => true
end

app/controllers/application_controller.rb
# Credda
# Copyright (C) 2012-2012 by Bryce Senz
#------------------------------------------------------------------------------ 
class ApplicationController < ActionController::Base
  before_filter :check_mobile
  check_authorization :unless => :devise_controller?
  
  # Defines how the application will respond to different format requests
  # TODO: Validate that all permissions are acceptable and confirm this logic
  #----------------------------------------------------------------------------
  respond_to :html
#  respond_to :js
#  respond_to :json, :xml, :except => [:edit, :update]
#  respond_to :atom, :csv, :rss, :only => :index

  rescue_from ActiveRecord::RecordNotFound, :with => :respond_to_not_found
  rescue_from CanCan::AccessDenied, :with => :respond_to_access_denied
  
  # SECURITY - Protect Form IDs from forgery
  #----------------------------------------------------------------------------
  protect_from_forgery
 
 # Helpers
  helper_method :current_user
  
  def current_user
    begin
      return current_customer unless current_customer.nil?
      return current_store unless current_store.nil?
      return current_employee unless current_employee.nil?
    rescue
      return nil
    end
  end

  private
  def current_ability
    Ability.new(current_user)
  end

  def check_mobile
    return (request.user_agent =~ /Mobile|webOS/)
  end

  #----------------------------------------------------------------------------
  def respond_to_not_found
    flash[:alert] = t(:msg_not_found)

    respond_to do |format|
      format.html { redirect_to user_home_path }
      format.js   { render(:update) { |page| page.reload } }
      format.json { render :text => flash[:alert], :status => :not_found }
      format.xml  { render :text => flash[:alert], :status => :not_found }
    end
  end

  #----------------------------------------------------------------------------
  def respond_to_access_denied
    flash[:alert] = t(:msg_not_authorized)

    respond_to do |format|
      format.html { redirect_to user_home_path }
      format.js   { render(:update) { |page| page.reload } }
      format.json { render :text => flash[:alert], :status => :unauthorized }
      format.xml  { render :text => flash[:alert], :status => :unauthorized }
    end
  end
  
  def user_home_path
    return customer_home_path if current_user.is_a?(Customer)
    return store_home_path if current_user.is_a?(Store)
    return employee_home_path if current_user.is_a?(Employee)
    return home_path
  end
end

app/controllers/customer/application_controller.rb
class Customer::ApplicationController < ::ApplicationController
  layout 'customer_application'
  before_filter :check_scope_conflict

  before_filter :authenticate_customer!
  before_filter :get_customer

  def current_user
    @current_user = current_customer unless current_customer.nil?
  end
  
  def get_customer
    @current_customer = current_customer
  end

  private
  def check_scope_conflict
    redirect_to home_path if (!(current_user.nil?) && (current_customer.nil?))
  end
end

app/controllers/customer/applications_controller.rb
class Customer::ApplicationsController < Customer::BaseController
  include ActiveModel::ForbiddenAttributesProtection
  load_and_authorize_resource

  # GET /store/applications
  #-----------------------------------------------------------------------
  def index
    @applications = Application.all
    respond_with(:customer, @applications)
  end

  # GET /store/applications/1
  #-------------------------------------------------------------------
  def show
    @application = Application.find(params[:id])
    respond_with(:customer, @application)
  end
  
  # PUT /store/applications/1/claim
  #-------------------------------------------------------------------
  def claim
    @application = Application.find(params[:id])
    @application.customer_account_number = current_customer.account_number

    if @application.claim
      flash[:notice] = "Successfully claimed application."
    else
      flash[:alert] = YAML.load_file("#{Rails.root}/config/locales/devise.en.yml")['en']['devise']['failure']['invalid_data']
    end
    respond_with(:customer, @application)
  end

  # GET /store/applications/1/edit
  #-------------------------------------------------------------------
  def edit
    @product_types = ["Tire"]
    @application = Application.find(params[:id])
    respond_with(:customer, @application)
  end

  # PUT /employee/applications/1
  #-----------------------------------------------------------------
  def update
    @product_types = ["Tire"]
    @application = Application.find(params[:id])

    if @application.update_attributes(update_application_params)
      flash[:notice] = "Successfully updated application."
      if @application.submit
        credit_decision = CreditDecision.new(:application => @application)
        if credit_decision.save
          @application.approve
          flash[:alert] = "Application approved."
        end
      else
        flash[:alert] = "Submission Unsuccessful."
      end
    else
      flash[:notice] = "Updating application failed."
    end
    respond_with(:customer, @application)
  end
  
  # DELETE /store/applications/1
  #-------------------------------------------------------------------
  def destroy
    @application = Application.find(params[:id])
    @application.destroy
    flash[:notice] = "Successfully destroyed application."
    respond_with(:customer, @application)
  end

  private
  def update_application_params
    params.require(:application).permit( 
      :time_at_address, :rent_or_own, :rent_payment )
  end
end

app/controllers/customer/auth_controller.rb
class Customer::AuthController < Customer::ApplicationController
  before_filter :authenticate_customer!, :except => [:access_token]
  skip_before_filter :verify_authenticity_token, :only => [:access_token]

  #TODO: re-evaluate this; maybe this is how I controll access for each client?
  skip_authorization_check

  # GET /authorize
  def authorize
    AccessGrant.prune!
    access_grant = current_customer.access_grants.create({:client => application, :state => params[:state]}, :without_protection => true)
    redirect_to access_grant.redirect_uri_for(params[:client_id])
  end

  # GET /access_token
  def access_token
    application = Client.authenticate(params[:client_id], params[:client_secret])

    if application.nil?
      render :json => {:error => "Could not find application"}
      return
    end

    access_grant = AccessGrant.authenticate(params[:code], application.id)
    if access_grant.nil?
      render :json => {:error => "Could not authenticate access code"}
      return
    end

    access_grant.start_expiry_period!
    render :json => {:access_token => access_grant.access_token, :refresh_token => access_grant.refresh_token, :expires_in => Devise.timeout_in.to_i}
  end

  def failure
    render :text => "ERROR: #{params[:message]}"
  end

  def customer
    hash = {
      :provider => 'credda',
      :id => current_customer.id.to_s,
      :info => {
         :email      => current_customer.email,
      },
      :extra => {
         :first_name => current_customer.first_name,
         :last_name  => current_customer.last_name
      }
    }

    render :json => hash.to_json
  end

  # Incase, we need to check timeout of the session from a different application!
  # This will be called ONLY if the user is authenticated and token is valid
  # Extend the UserManager session
  def isalive
    warden.set_user(current_customer, :scope => :customer)
    response = { 'status' => 'ok' }

    respond_to do |format|
      format.any { render :json => response.to_json }
    end
  end

  protected
  def application
    @application ||= Client.find_by_app_id(params[:client_id])
  end
end

app/views/customer/applications/_product_fields.html.slim
div.row
  div.large-4.columns
    = f.label "Product Type"
    = f.select :type, @product_types, {}, :disabled => true
  div.large-8.columns
    = f.label "Name"
    = f.text_field :name, :disabled => true
div.row
  div.large-4.columns
    = f.label "Price"
    = f.text_field :price, :disabled => true
  div.large-8.columns
    = f.label "ID Number"
    = f.text_field :id_number, :disabled => true
div.row
  div.large-12.columns
    = f.label "Description"
    = f.text_area :description, :disabled => true

app/views/customer/applications/edit.html.slim
= provide(:title, 'Edit Application')

div.row
  div.large-12.columns
    = nested_form_for(@application, :url => customer_application_path(@application), :method => :put, :html => { :class => "" }) do |f|
      fieldset
        legend Store Details
        div.row
          div.large-4.columns
            = f.label "Account Number"
            = f.text_field :store_account_number, :disabled => true
          div.large-8.columns
            = f.label "Name"
            = f.text_field :store_name, :disabled => true
      fieldset
        legend Products
        = f.fields_for :products
      fieldset
        legend Customer Details
        div.row
          div.large-12.columns
            = f.label "When did you move into this address?"
            = f.date_select :time_at_address, :discard_day => true
        div.row
          div.large-12.columns
            = f.label "Do you rent or own this property"
            = f.select :rent_or_own, ["Rent", "Own"], {}
        div.row
          div.large-12.columns
            = f.label "What is your monthly rent/mortgage payment"
            = f.text_field :rent_payment, :placeholder => "200"
      = f.submit "Submit Application", :class => "radius button"
      = link_to "Cancel", customer_application_path(@application), :class => "button radius secondary"

app/views/customer/applications/index.html.slim
= provide(:title, "Applications")

div.row
  div.large-12.columns
    - if (@applications.nil?) || (@applications.empty?)
      p There are currently no stores.
    - else
      table
        thead
          tr
            th Account Number
            th Name
            th Status
            th
            th
            th
        tbody
          - @applications.each do |application|
            tr
              td = application.application_number
              td = application.customer_account_number
              td = application.store_account_number
div.row
  div.large-12.columns
    = link_to "New Application", new_store_application_path, :class => "button radius small"

app/views/customer/applications/new.html.slim
= provide(:title, 'New Employee')

div.row
  div.large-8.columns
    = nested_form_for(@application, :url => store_applications_path, :method => :post, :html => { :class => "" }) do |f|
      fieldset
        legend Store Details
        div.row
          div.large-4.columns
            = f.label "Account Number"
            = f.text_field :store_account_number, :value => "#{current_store.account_number}", :disabled => true
          div.large-8.columns
            = f.label "Name"
            = f.text_field :store_name, :value => "#{current_store.name}", :disabled => true
      fieldset
        legend Customer Details
        div.row
          div.large-6.columns
            = f.label "Matching Email"
            = f.text_field :matching_email, :placeholder => "customer@email.com"
      fieldset
        legend Products
        = f.fields_for :products
        = f.link_to_add "Add a product", :products, :class => "button radius small"
      = f.submit "Start Application", :class => "radius button"

app/views/customer/applications/show.html.slim
= provide(:title, "Application")

div.row
  div.large-12.columns
    h2 = "#{@application.store_name} (No: #{@application.store_account_number})"
    h3 = "Status: <span class='round label'>#{@application.state}</span>".html_safe
    h3 Products
    - @application.products.each do |product|
      div.panel
        div.row
          div.large-8.columns
            = product.name
          div.large-4.columns
            = product.price
div.row
  div.large-3.columns
    = link_to "Continue Application", edit_customer_application_path(@application), :class => "button radius small"
  div.large-3.columns
    = link_to "Cancel Application", customer_application_path(@application), :method => :delete, :class => "button secondary radius small"